# TODO: Translation updated at 2026-06-29 18:49

translate spanish strings:

    # game/scripts/credits.rpy:20
    old "About"
    new "Acerca de"

    # game/scripts/credits.rpy:35
    old "Supporters"
    new "Colaboradores"

    # game/scripts/credits.rpy:39
    old "Soundtrack"
    new "Banda sonora"

    # game/scripts/credits.rpy:53
    old "{size=22}\nDeveloped by: ZetanDS\nRenders & Animations: ZetanDS, Hadham\nStory: ZetanDS\nDialogues: ZetanDS, CynicalADM\nCode: Paz\nUI: Paz, Hadham\n\nCommunity translators:\nSpanish: Darax\nRussian: Kasatik\nItalian: Eagle1900\nSimplified Chinese: Aler, Wert\nTraditional Chinese: AHHCrazy\nTurkish: BoxxO\nFrench: Gryff\n\nAnd a sincere thank you to the community for their continued support, helpful bug reports, and constructive discussions!\n\nMade with {a=https://www.renpy.org/}Ren'Py{/a} [renpy.version_only]\n{size=18}[renpy.license!t]{/size}\n\nRenders created with Daz3d\n"
    new "{size=22}\nDesarrollado por: ZetanDS\nRenders y animaciones: ZetanDS, Hadham\nHistoria: ZetanDS\nDiálogos: ZetanDS, CynicalADM\nCódigo: Paz\nInterfaz: Paz, Hadham\n\nTraductores de la comunidad:\nEspañol: Darax\nRuso: Kasatik\nItaliano: Eagle1900\nChino simplificado: Aler, Wert\nChino tradicional: AHHCrazy\nTurco: BoxxO\nFrancés: Gryff\n\n¡Y nuestro más sincero agradecimiento a la comunidad por su apoyo constante, sus útiles informes de errores y sus debates constructivos!\n\nCreado con {a=https://www.renpy.org/}Ren'Py{/a} [renpy.version_only]\n{size=18}[renpy.license!t]{/size}\n\nRenders creados con Daz3d\n"

    # game/scripts/credits.rpy:87
    old "\nFirst and foremost:{size=22}\nTo everybody who enjoys playing this game and see it develop over time;\na sincere thank you for showing your support, for spreading the word and for the compliments and constructive\ncriticism you send my way.\nYour support helps out greatly and maybe even eventually lets me hire people to achieve more efficient game development.\n{/size}\nSpecial mention goes to the people who support the game in various ways:{size=22}\n- Ivy's Stalker and GetOutOfMyLab for their efforts on Discord.\n- Eleven12 for his generous startup support.\n{/size}\nFinally, many thanks to all the Legates, Elders and Ancestors on Patreon and SubscribeStar:\n"
    new "\nAntes que nada:{size=22}\nA todos los que disfrutáis jugando a este juego y viendo cómo evoluciona con el tiempo;\nmi más sincero agradecimiento por vuestro apoyo, por darlo a conocer y por los elogios y críticas\nconstructivas que me hacéis llegar.\nVuestro apoyo es de gran ayuda y quizá algún día incluso me permita contratar a más personas para agilizar el desarrollo del juego.\n{/size}\nMención especial para quienes apoyan el juego de distintas formas:{size=22}\n- Ivy's Stalker y GetOutOfMyLab, por su labor en Discord.\n- Eleven12, por su generoso apoyo en los inicios.\n{/size}\nPor último, muchas gracias a todos los Legados, Ancianos y Ancestros de Patreon y SubscribeStar:\n"

    # game/scripts/credits.rpy:108
    old "\nIf your name is not on the list {color=#9f8461}({/color}or it's in the list and you'd prefer to have it removed{color=#9f8461}){/color} please contact me."
    new "\nSi tu nombre no aparece en la lista {color=#9f8461}({/color}o aparece y prefieres que lo retire{color=#9f8461}){/color}, ponte en contacto conmigo."

    # game/scripts/credits.rpy:118
    old "\nMusic:{size=22}\nThe music used in the game is either released under a CC / CCA license and listed down below\nor purchased from marketplaces for digital assets.\nShould that not be the case, it was not my intention to spread your work without permission.\nPlease contact me to be properly accredited or have your works removed from the game if you wish.\n\nI am not affiliated with the creators in any way, and I do not claim ownership over their respective creations.\n{/size}\nCC / CCA Artists:{size=22}\n- {a=https://www.youtube.com/channel/UC1KJEk-EZMmDF9DJKMK5OCQ}Aim to Head Official{/a}\n- {a=https://www.youtube.com/user/teknoaxe}TeknoAXE's Royalty Free Music{/a}\n- {a=https://www.youtube.com/channel/UCd9s9Vq6aGYSRNjlTpZa3pA}The Sound Club{/a}\n- {a=https://www.youtube.com/user/VivEKhsihbA}Vivek Abhishek{/a}\n- {a=https://www.youtube.com/channel/UC_6hQy4elsyHhCOskZo0U5g}White Bat Audio{/a}\n- {a=https://www.youtube.com/c/WhitesandComposer/featured}Whitesand{/a}\n- {a=https://www.youtube.com/c/kmmusic/featured}Kevin MacLeod{/a}\n{/size}\n\n------------------------------------------------------\n{size=30}{color=#9f8461}S{/color}{/size}ounds are partly provided by freesound.org and mixkit.co under the creative commons or attribution license and acquired from other marketplaces for digital assets.\n\nCCA Sounds:{size=22}\n- Large Crash by Cgeffex\n- Car Breaking Skid 01 by Medartimus\n- Car start by enric592\n- 2 Car horns by alukahn\n- WoodenFloorFootsteps_Boots_02 by Lex777\n- Neon ON OFF by SkyernAklea\n- horror ambience LONG 190624_0042 by klankbeeld\n- Door sheet metal by cdrk\n- RoomTone EmptyClassRoom 01 by {a=http://www.freesound.org/people/klankbeeld}klankbeeld{/a}\n- Nasty Knife Stab 2 by {a=https://freesound.org/people/Aris621}Aris621{/a}\n{/size}\n"
    new "\nMúsica:{size=22}\nLa música utilizada en el juego se ha publicado bajo una licencia CC / CCA y figura a continuación,\no se ha adquirido en mercados de recursos digitales.\nSi no fuera así, nunca fue mi intención difundir tu obra sin permiso.\nPonte en contacto conmigo si deseas que se te acredite debidamente o que tu obra sea retirada del juego.\n\nNo estoy afiliado de ningún modo con los creadores ni reclamo la propiedad de sus respectivas obras.\n{/size}\nArtistas CC / CCA:{size=22}\n- {a=https://www.youtube.com/channel/UC1KJEk-EZMmDF9DJKMK5OCQ}Aim to Head Official{/a}\n- {a=https://www.youtube.com/user/teknoaxe}TeknoAXE's Royalty Free Music{/a}\n- {a=https://www.youtube.com/channel/UCd9s9Vq6aGYSRNjlTpZa3pA}The Sound Club{/a}\n- {a=https://www.youtube.com/user/VivEKhsihbA}Vivek Abhishek{/a}\n- {a=https://www.youtube.com/channel/UC_6hQy4elsyHhCOskZo0U5g}White Bat Audio{/a}\n- {a=https://www.youtube.com/c/WhitesandComposer/featured}Whitesand{/a}\n- {a=https://www.youtube.com/c/kmmusic/featured}Kevin MacLeod{/a}\n{/size}\n\n------------------------------------------------------\n{size=30}{color=#9f8461}L{/color}{/size}os sonidos proceden en parte de freesound.org y mixkit.co bajo licencias Creative Commons o de atribución, y también se han adquirido en otros mercados de recursos digitales.\n\nSonidos CCA:{size=22}\n- Large Crash, de Cgeffex\n- Car Breaking Skid 01, de Medartimus\n- Car start, de enric592\n- 2 Car horns, de alukahn\n- WoodenFloorFootsteps_Boots_02, de Lex777\n- Neon ON OFF, de SkyernAklea\n- horror ambience LONG 190624_0042, de klankbeeld\n- Door sheet metal, de cdrk\n- RoomTone EmptyClassRoom 01, de {a=http://www.freesound.org/people/klankbeeld}klankbeeld{/a}\n- Nasty Knife Stab 2, de {a=https://freesound.org/people/Aris621}Aris621{/a}\n{/size}\n"

