# TODO: Translation updated at 2026-03-05 21:40

translate spanish strings:

    # game/scripts/credits.rpy:20
    old "About"
    new "Acerca de"

    # game/scripts/credits.rpy:26
    old "Credits"
    new "Créditos"

    # game/scripts/credits.rpy:35
    old "Supporters"
    new "Colaboradores"

    # game/scripts/credits.rpy:39
    old "Soundtrack"
    new "Banda sonora"

    # game/scripts/credits.rpy:53
    old "{size=22}\nDeveloped by: ZetanDS\nRenders & Animations: ZetanDS, Hadham\nStory: ZetanDS\nDialogues: ZetanDS, CynicalADM\nCode: Paz\nUI: Paz, Hadham\n\nCommunity translators:\nSpanish: Darax\nRussian: Kasatik\nItalian: Eagle1900\nSimplified Chinese: Aler, Wert\nTraditional Chinese: AHHCrazy\nTurkish: BoxxO\nFrench: Gryff\n\nAnd a sincere thank you to the community for their continued support, helpful bug reports, and constructive discussions!\n\nMade with {a=https://www.renpy.org/}Ren'Py{/a} [renpy.version_only]\n{size=18}[renpy.license!t]{/size}\n\nRenders created with Daz3d\n"
    new "{size=22}\nDesarrollado por: ZetanDS\nRenders y animaciones: ZetanDS, Hadham\nHistoria: ZetanDS\nDiálogos: ZetanDS, CynicalADM\nCódigo: Paz\nInterfaz: Paz, Hadham\n\nTraductores de la comunidad:\nEspañol: Darax\nRuso: Kasatik\nItaliano: Eagle1900\nChino simplificado: Aler, Wert\nChino tradicional: AHHCrazy\nTurco: BoxxO\nFrancés: Gryff\n\nY un sincero agradecimiento a la comunidad por su continuo apoyo, sus útiles informes de errores y sus constructivos debates.\n\nHecho con {a=https://www.renpy.org/}Ren'Py{/a} [renpy.version_only]\n{size=18}[renpy.license!t]{/size}\n\nRenders creados con Daz3d\n"

    # game/scripts/credits.rpy:87
    old "\nFirst and foremost:{size=22}\nTo everybody who enjoys playing this game and see it develop over time;\na sincere thank you for showing your support, for spreading the word and for the compliments and constructive\ncriticism you send my way.\nYour support helps out greatly and maybe even eventually lets me hire people to achieve more efficient game development.\n{/size}\nSpecial mention goes to the people who support the game in various ways:{size=22}\n- Ivy's Stalker and GetOutOfMyLab for their efforts on Discord.\n- Eleven12 for his generous startup support.\n{/size}\nFinally, many thanks to all the Legates, Elders and Ancestors on Patreon and SubscribeStar:\n"
    new "\nAnte todo:{size=22}\nA todos los que disfrutáis jugando a este juego y lo veis evolucionar con el tiempo;\nun sincero agradecimiento por vuestro apoyo, por correr la voz y por los cumplidos y críticas\nconstructivas que me hacéis llegar.\nVuestro apoyo ayuda enormemente y quizá incluso me permita contratar gente para lograr un desarrollo más eficiente.\n{/size}\nUna mención especial a la gente que apoya el juego de diversas formas:{size=22}\n- Ivy's Stalker y GetOutOfMyLab por su esfuerzo en Discord.\n- Eleven12 por su generoso apoyo inicial.\n{/size}\nPor último, muchas gracias a todos los Legados, Ancianos y Ancestros en Patreon y SubscribeStar:\n"

    # game/scripts/credits.rpy:108
    old "\nIf your name is not on the list {color=#9f8461}({/color}or it's in the list and you'd prefer to have it removed{color=#9f8461}){/color} please contact me."
    new "\nSi tu nombre no aparece en la lista {color=#9f8461}({/color}o está y prefieres que lo retire{color=#9f8461}){/color}, ponte en contacto conmigo."

    # game/scripts/credits.rpy:118
    old "\nMusic:{size=22}\nThe music used in the game is either released under a CC / CCA license and listed down below\nor purchased from marketplaces for digital assets.\nShould that not be the case, it was not my intention to spread your work without permission.\nPlease contact me to be properly accredited or have your works removed from the game if you wish.\n\nI am not affiliated with the creators in any way, and I do not claim ownership over their respective creations.\n{/size}\nCC / CCA Artists:{size=22}\n- {a=https://www.youtube.com/channel/UC1KJEk-EZMmDF9DJKMK5OCQ}Aim to Head Official{/a}\n- {a=https://www.youtube.com/user/teknoaxe}TeknoAXE's Royalty Free Music{/a}\n- {a=https://www.youtube.com/channel/UCd9s9Vq6aGYSRNjlTpZa3pA}The Sound Club{/a}\n- {a=https://www.youtube.com/user/VivEKhsihbA}Vivek Abhishek{/a}\n- {a=https://www.youtube.com/channel/UC_6hQy4elsyHhCOskZo0U5g}White Bat Audio{/a}\n- {a=https://www.youtube.com/c/WhitesandComposer/featured}Whitesand{/a}\n- {a=https://www.youtube.com/c/kmmusic/featured}Kevin MacLeod{/a}\n{/size}\n\n------------------------------------------------------\n{size=30}{color=#9f8461}S{/color}{/size}ounds are partly provided by freesound.org and mixkit.co under the creative commons or attribution license and acquired from other marketplaces for digital assets.\n\nCCA Sounds:{size=22}\n- Large Crash by Cgeffex\n- Car Breaking Skid 01 by Medartimus\n- Car start by enric592\n- 2 Car horns by alukahn\n- WoodenFloorFootsteps_Boots_02 by Lex777\n- Neon ON OFF by SkyernAklea\n- horror ambience LONG 190624_0042 by klankbeeld\n- Door sheet metal by cdrk\n- RoomTone EmptyClassRoom 01 by {a=http://www.freesound.org/people/klankbeeld}klankbeeld{/a}\n- Nasty Knife Stab 2 by {a=https://freesound.org/people/Aris621}Aris621{/a}\n{/size}\n"
    new "\nMúsica:{size=22}\nLa música utilizada en el juego se publica bajo licencia CC / CCA y aparece listada a continuación\no se ha adquirido en mercados de activos digitales.\nSi no fuera el caso, no es mi intención difundir tu trabajo sin permiso.\nPor favor, ponte en contacto conmigo para que te acredite adecuadamente o para retirar tus obras del juego si así lo deseas.\n\nNo estoy afiliado a los creadores de ningún modo, y no reclamo la propiedad de sus respectivas creaciones.\n{/size}\nArtistas CC / CCA:{size=22}\n- {a=https://www.youtube.com/channel/UC1KJEk-EZMmDF9DJKMK5OCQ}Aim to Head Official{/a}\n- {a=https://www.youtube.com/user/teknoaxe}TeknoAXE's Royalty Free Music{/a}\n- {a=https://www.youtube.com/channel/UCd9s9Vq6aGYSRNjlTpZa3pA}The Sound Club{/a}\n- {a=https://www.youtube.com/user/VivEKhsihbA}Vivek Abhishek{/a}\n- {a=https://www.youtube.com/channel/UC_6hQy4elsyHhCOskZo0U5g}White Bat Audio{/a}\n- {a=https://www.youtube.com/c/WhitesandComposer/featured}Whitesand{/a}\n- {a=https://www.youtube.com/c/kmmusic/featured}Kevin MacLeod{/a}\n{/size}\n\n------------------------------------------------------\n{size=30}{color=#9f8461}S{/color}{/size}onidos proporcionados en parte por freesound.org y mixkit.co bajo licencia creative commons o atribución, y adquiridos en otros mercados de activos digitales.\n\nSonidos CCA:{size=22}\n- Large Crash por Cgeffex\n- Car Breaking Skid 01 por Medartimus\n- Car start por enric592\n- 2 Car horns por alukahn\n- WoodenFloorFootsteps_Boots_02 por Lex777\n- Neon ON OFF por SkyernAklea\n- horror ambience LONG 190624_0042 por klankbeeld\n- Door sheet metal por cdrk\n- RoomTone EmptyClassRoom 01 por {a=http://www.freesound.org/people/klankbeeld}klankbeeld{/a}\n- Nasty Knife Stab 2 por {a=https://freesound.org/people/Aris621}Aris621{/a}\n{/size}\n"